name: CoriolisMedicalPhysics
favicon: null
layout_spectrum: 0.18915563845075667
typography_spectrum: 0.5253556363750249
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.019665988627821207
  lightness: 0.49389950605109334
  saturation: 0.9590207876171917
  rhythmicContrast: 0.17438681982457638
purpose: []
